on:
  push:
    branches: 
     - master

name: Auto Release Publish

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [10]
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      # add cache to improve workflow execution time
      - name: Cache .gradle/caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Cache .gradle/wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -s
      - name: Shadow Jar
        run: ./gradlew shadowJar
      - name: Rename Jar
        run: 
          ls;
          cd build/libs;
          ls;
          file=`ls | grep 'lua-mirai.*jar'`;
          mv $file lua-mirai.jar
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
#          body: |
#            Changes in this Release
#            - First Change
#            - Second Change
          body_path: ./docs/updatedoc/latest.md
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - uses: actions/upload-artifact@v2
        with:
              name: my-artifact
              path: ./build/libs/lua-mirai.jar
          
